// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProjectInfo() {
  return window['go']['main']['App']['GetProjectInfo']();
}

export function GetProxyURL() {
  return window['go']['main']['App']['GetProxyURL']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function SelectProjectDirectory() {
  return window['go']['main']['App']['SelectProjectDirectory']();
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function StartProxy(arg1) {
  return window['go']['main']['App']['StartProxy'](arg1);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}
