// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProjectInfo():Promise<Record<string, any>>;

export function GetProxyURL():Promise<string>;

export function GetStatus():Promise<Record<string, any>>;

export function SelectProjectDirectory():Promise<string>;

export function SetAPIKey(arg1:string):Promise<void>;

export function StartProxy(arg1:string):Promise<string>;

export function StopProxy():Promise<string>;
